### ISSUE TITLE
Add an example link to readme

### ISSUE THREAD

**Issue by AviKKi** [AviKKi/hover-preview#1]
host [this example](https://github.com/AviKKi/hover-preview/blob/main/example/index.html) on a platform like netlify or vercel.

and add it's link to readme.md file.

**Comment by JohJohan** [comment]
I think this is the best we can do https://github.com/AviKKi/hover-preview/pull/3 otherwise you have to setup `netlify or vercel` because you have ownership of your repo

**Comment by Gilbishkosma** [comment]
Hii @AviKKi , i have added a demo link in the read me file and also updated the example/index.html file, the example is hosted using surge, Here is the link(https://hover-preview.surge.sh) .  Please accept the #5 PR . Thanks 😺
