### ISSUE TITLE
Add code linter and precommit hooks

### ISSUE THREAD

**Issue by AviKKi** [AviKKi/hover-preview#4]
- [x] eslint  
- [x] husky

**Comment by Bhavesh27** [comment]
@AviKKi Can you please assign me the issue. I can work on it.

**Comment by baycak** [comment]
Hi, I'd would like to work on this issue

**Comment by Bhavesh27** [comment]
@AviKKi https://github.com/AviKKi/hover-preview/pull/6 Added husky for precommit hook and setup eslint.

**Comment by AviKKi** [comment]
@bayucakra20 seems like @Bhavesh27 has already made a PR, there seems to be a bug in the code, can you work on [this](https://github.com/AviKKi/hover-preview/issues/7)?

**Comment by Bhavesh27** [comment]
@AviKKi Added lint:fix step and fixed all linting error as well.

**Comment by Bhavesh27** [comment]
@AviKKi Done all the changes.
