### ISSUE TITLE
Timeout/Interval bug

### ISSUE THREAD

**Issue by AviKKi** [AviKKi/hover-preview#7]
There is a bug in this plugin 

Visit [this website](https://nostalgic-boyd-d0a053.netlify.app/), hover over an image, then move your cursor very fast in and out of the image, the images will start flickering which is not expected they only change after a delay of `500ms`

I'm not sure what is happening maybe `mouseleave` event is not registered and `mousein` event is registered twice thrice by moving cursor in and out.

### Possible patches
1. using correct events from mouseleave, mouseout, mousein .... may fix this issue
1. set a timeout and interval variable and avoid setting multiple timeout and intervals at once.
or maybe
Find out what is causing the race condition and a better way to code this plugin.

**Comment by LoganxDev** [comment]
I'd like to take a shot at this one. :)

**Comment by AviKKi** [comment]
@LoganxDev go for it

**Comment by rohansp** [comment]
@AviKKi I would like to contribute. I see all issues are taken up. Do you have any open issues?

**Comment by joshnho** [comment]
Hi i would like to try this out also

**Comment by AviKKi** [comment]
Hello @rohansp and @joshnho I currently don't have any more issue, if you want to contribute you can raise a feature request and work on it.

Or star/watch the repo for upcoming issues.

**Comment by AviKKi** [comment]
fixed in https://github.com/AviKKi/hover-preview/pull/13
